# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kr10
  joint_model_group_pose: kr10_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - kr10_joint1
    - kr10_joint2
    - kr10_joint3
    - kr10_joint4
    - kr10_joint5
    - kr10_joint6
    - kr60_joint1
    - kr60_joint2
    - kr60_joint3
    - kr60_joint4
    - kr60_joint5
    - kr60_joint6
    - kr60_finger_joint1
    - kr60_finger_joint2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []